name: naytto
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  flutter_riverpod: ^2.4.9
  riverpod: ^2.4.9
  google_fonts: ^6.1.0
  firebase_auth: ^4.17.2
  go_router: ^13.1.0
  riverpod_annotation: ^2.3.3
  intl: ^0.18.1
  firebase_ui_firestore: ^1.6.1
  colorful_safe_area: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_lint: ^2.3.7
  custom_lint: ^0.5.11
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  assets:
  - assets/talo2.jpg