// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2vn1mKdMnVqqIIBUmq0yUIjs1IW07-9M',
    appId: '1:412461117322:web:d21487fccfaa3b39e66273',
    messagingSenderId: '412461117322',
    projectId: 'housingcooperative-827c8',
    authDomain: 'housingcooperative-827c8.firebaseapp.com',
    storageBucket: 'housingcooperative-827c8.appspot.com',
    measurementId: 'G-GSHP2BJ03H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUVp9D8n75inLrQOJAsqhPrZmYBeWsfMw',
    appId: '1:412461117322:android:1635efbd4e828456e66273',
    messagingSenderId: '412461117322',
    projectId: 'housingcooperative-827c8',
    storageBucket: 'housingcooperative-827c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuvsd0Nij7e0jcrcfXbX7jkHw5nwUKtbo',
    appId: '1:412461117322:ios:0b167d00dd24336ee66273',
    messagingSenderId: '412461117322',
    projectId: 'housingcooperative-827c8',
    storageBucket: 'housingcooperative-827c8.appspot.com',
    iosBundleId: 'com.example.naytto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuvsd0Nij7e0jcrcfXbX7jkHw5nwUKtbo',
    appId: '1:412461117322:ios:dff3e06d354862dfe66273',
    messagingSenderId: '412461117322',
    projectId: 'housingcooperative-827c8',
    storageBucket: 'housingcooperative-827c8.appspot.com',
    iosBundleId: 'com.example.naytto.RunnerTests',
  );
}
